## Short-term Mortality: Class Balancing (30-day)

```r
# ------------------------------------------------------------------------------
# Module: 2_ROSE_balancing_short.R
# Objective: Adjust class imbalance for 30-day mortality outcome following AMI
# Input: Preprocessed dataset generated by 1_data_preparation_short.R
# Output: Balanced dataset for downstream logistic regression modeling
# ------------------------------------------------------------------------------
# Description:
# This script applies the ROSE (Random Over-Sampling Examples) method to correct
# class imbalance in 30-day acute myocardial infarction (AMI) mortality outcomes.
# Based on the observed real-world event rate (7.4%), the default threshold of 0.5
# may result in suboptimal model sensitivity. ROSE synthetically augments the minority
# class to support more stable training and improve classification performance.
#
# The balanced dataset generated in this module is subsequently used in:
# - Module 3: Logistic regression model fitting and nomogram derivation
# ------------------------------------------------------------------------------
```

```r
library(ROSE)
library(dplyr)

# Assuming 'data' is already loaded from the previous step
# Example only: data <- readRDS("preprocessed_data.RDS")

# Ensure binary outcome is labeled 0/1
if (!"event_status_30" %in% names(data)) stop("Missing outcome variable: event_status_30")

# Apply ROSE to balance minority and majority classes
set.seed(123)  # for reproducibility
rose_data <- ROSE(event_status_30 ~ ., data = data, seed = 123)$data

# Check class distribution after balancing
cat("\nClass distribution after ROSE balancing:\n")
print(table(rose_data$event_status_30))

# The balanced dataset is now ready for logistic regression modeling
```
